# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cUaSqsN7jumbSIIyGxVGNlcwo9CIPB67
"""

from google.colab import files
uploaded=files.upload()
uploaded1=files.upload()
uploaded2=files.upload()

import io
anfis=io.BytesIO(uploaded['anfis.py'])
mfDerivs=io.BytesIO(uploaded1['mfDerivs.py'])
membershipfunction=io.BytesIO(uploaded2['membershipfunction.py'])

!pip install scikit-fuzzy

import anfis
import mfDerivs
import skfuzzy
import membershipfunction
import numpy

uploaded3=files.upload()

import pandas as pd
dataset=pd.read_csv(io.BytesIO(uploaded3['Typhoid-train.csv']))
dataset.head()

target=dataset.pop('Prognosis')

target.shape

mf = [[['gaussmf',{'mean':0.,'sigma':1.}],['gaussmf',{'mean':-1.,'sigma':2.}],['gaussmf',{'mean':-4.,'sigma':10.}],['gaussmf',{'mean':-7.,'sigma':7.}]],
            [['gaussmf',{'mean':1.,'sigma':2.}],['gaussmf',{'mean':2.,'sigma':3.}],['gaussmf',{'mean':-2.,'sigma':10.}],['gaussmf',{'mean':-10.5,'sigma':5.}]],
      [['gaussmf',{'mean':0.,'sigma':1.}],['gaussmf',{'mean':-1.,'sigma':2.}],['gaussmf',{'mean':-4.,'sigma':10.}],['gaussmf',{'mean':-7.,'sigma':7.}]],
            [['gaussmf',{'mean':1.,'sigma':2.}],['gaussmf',{'mean':2.,'sigma':3.}],['gaussmf',{'mean':-2.,'sigma':10.}],['gaussmf',{'mean':-10.5,'sigma':5.}]]]

mfc=membershipfunction.MemFuncs(mf)
anf=anfis.ANFIS(dataset, target, mfc)
anf.trainHybridJangOffLine(epochs=10)

anf.plotErrors()
anf.plotResults()

print(" Severity of each symptoms lies between 0 ~ 10\n")
fever = float(input(" Enter the severity of fever: "))
stomachache = float(input(" Enter the severity of stomachache: "))
drycough = float(input(" Enter the severity of drycough: "))
coldchill = float(input(" Enter the severity of coldchill: "))
X = numpy.asarray([[fever,stomachache,drycough,coldchill]])
y=anfis.predict(anf,X)

if y>=5.7:
  print(" Typhoid severe, low fever: ",y)
elif y>=2.8:
  print(" Typhoid mild, High fever: ",y)
else:
  print(" Typhoid low, low fever: ",y)
